### ISSUE TITLE
拓展屏采集问题

### ISSUE THREAD

**Issue by liandne** [hotkidfamily/magnifier-sample#1]
当host_windows 的rect 为 拓展屏区域时 OnMagImageScalingCallback 会触发吗？我本地使用的时候无法触发获取到rgb数据

**Comment by hotkidfamily** [comment]
可以，但是有缺陷，主屏幕得分辨率不能比扩展屏小。 win 10 上测试得。

**Comment by hotkidfamily** [comment]
> 当host_windows 的rect 为 拓展屏区域时 OnMagImageScalingCallback 会触发吗？我本地使用的时候无法触发获取到rgb数据

可以，但是有缺陷，主屏幕得分辨率不能比扩展屏小。 win 10 上测试。

**Comment by liandne** [comment]
> > 当host_windows 的rect 为 拓展屏区域时 OnMagImageScalingCallback 会触发吗？我本地使用的时候无法触发获取到rgb数据
> 
> 如果 OnMagImageScalingCallback 要触发，需要 主屏幕的分辨率比扩展屏大才行。win10 上测试的。另外这个 api deprecated。要用 hook 的方式，放大镜程序可以放大，就可以捕捉。

hook方式具体是指？hook什么进程吗？放大镜程序？

**Comment by hotkidfamily** [comment]
> > > 当host_windows 的rect 为 拓展屏区域时 OnMagImageScalingCallback 会触发吗？我本地使用的时候无法触发获取到rgb数据
> > 
> > 
> > 如果 OnMagImageScalingCallback 要触发，需要 主屏幕的分辨率比扩展屏大才行。win10 上测试的。另外这个 api deprecated。要用 hook 的方式，放大镜程序可以放大，就可以捕捉。
> 
> hook方式具体是指？hook什么进程吗？放大镜程序？

mag是通过 d3d9 渲染的，hook d3d9 的 api 拿到渲染的内容，替换 OnMagImageScalingCallback 这个功能。
